//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigaManagerBettorClient.BettorClientService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BettorClientService.IBettorClientService")]
    public interface IBettorClientService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILigaManagerService/GetMatches", ReplyAction="http://tempuri.org/ILigaManagerService/GetMatchesResponse")]
        LigaManagerServer.Models.Match[] GetMatches(LigaManagerServer.Models.Season season);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILigaManagerService/GetMatches", ReplyAction="http://tempuri.org/ILigaManagerService/GetMatchesResponse")]
        System.Threading.Tasks.Task<LigaManagerServer.Models.Match[]> GetMatchesAsync(LigaManagerServer.Models.Season season);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILigaManagerService/GetBets", ReplyAction="http://tempuri.org/ILigaManagerService/GetBetsResponse")]
        LigaManagerServer.Models.Bet[] GetBets(LigaManagerServer.Models.Bettor bettor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILigaManagerService/GetBets", ReplyAction="http://tempuri.org/ILigaManagerService/GetBetsResponse")]
        System.Threading.Tasks.Task<LigaManagerServer.Models.Bet[]> GetBetsAsync(LigaManagerServer.Models.Bettor bettor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILigaManagerService/GetAllBets", ReplyAction="http://tempuri.org/ILigaManagerService/GetAllBetsResponse")]
        LigaManagerServer.Models.Bet[] GetAllBets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILigaManagerService/GetAllBets", ReplyAction="http://tempuri.org/ILigaManagerService/GetAllBetsResponse")]
        System.Threading.Tasks.Task<LigaManagerServer.Models.Bet[]> GetAllBetsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILigaManagerService/GetBettors", ReplyAction="http://tempuri.org/ILigaManagerService/GetBettorsResponse")]
        LigaManagerServer.Models.Bettor[] GetBettors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILigaManagerService/GetBettors", ReplyAction="http://tempuri.org/ILigaManagerService/GetBettorsResponse")]
        System.Threading.Tasks.Task<LigaManagerServer.Models.Bettor[]> GetBettorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILigaManagerService/GetBettor", ReplyAction="http://tempuri.org/ILigaManagerService/GetBettorResponse")]
        LigaManagerServer.Models.Bettor GetBettor(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILigaManagerService/GetBettor", ReplyAction="http://tempuri.org/ILigaManagerService/GetBettorResponse")]
        System.Threading.Tasks.Task<LigaManagerServer.Models.Bettor> GetBettorAsync(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILigaManagerService/GetSeasons", ReplyAction="http://tempuri.org/ILigaManagerService/GetSeasonsResponse")]
        LigaManagerServer.Models.Season[] GetSeasons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILigaManagerService/GetSeasons", ReplyAction="http://tempuri.org/ILigaManagerService/GetSeasonsResponse")]
        System.Threading.Tasks.Task<LigaManagerServer.Models.Season[]> GetSeasonsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILigaManagerService/GetTeams", ReplyAction="http://tempuri.org/ILigaManagerService/GetTeamsResponse")]
        LigaManagerServer.Models.SeasonToTeamRelation[] GetTeams(LigaManagerServer.Models.Season season);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILigaManagerService/GetTeams", ReplyAction="http://tempuri.org/ILigaManagerService/GetTeamsResponse")]
        System.Threading.Tasks.Task<LigaManagerServer.Models.SeasonToTeamRelation[]> GetTeamsAsync(LigaManagerServer.Models.Season season);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettorClientService/IsValidNickname", ReplyAction="http://tempuri.org/IBettorClientService/IsValidNicknameResponse")]
        bool IsValidNickname(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettorClientService/IsValidNickname", ReplyAction="http://tempuri.org/IBettorClientService/IsValidNicknameResponse")]
        System.Threading.Tasks.Task<bool> IsValidNicknameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettorClientService/AddBet", ReplyAction="http://tempuri.org/IBettorClientService/AddBetResponse")]
        bool AddBet(LigaManagerServer.Models.Bet bet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettorClientService/AddBet", ReplyAction="http://tempuri.org/IBettorClientService/AddBetResponse")]
        System.Threading.Tasks.Task<bool> AddBetAsync(LigaManagerServer.Models.Bet bet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettorClientService/ChangeBet", ReplyAction="http://tempuri.org/IBettorClientService/ChangeBetResponse")]
        bool ChangeBet(LigaManagerServer.Models.Bet bet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettorClientService/ChangeBet", ReplyAction="http://tempuri.org/IBettorClientService/ChangeBetResponse")]
        System.Threading.Tasks.Task<bool> ChangeBetAsync(LigaManagerServer.Models.Bet bet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettorClientService/GetBet", ReplyAction="http://tempuri.org/IBettorClientService/GetBetResponse")]
        LigaManagerServer.Models.Bet GetBet(LigaManagerServer.Models.Match match, LigaManagerServer.Models.Bettor bettor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettorClientService/GetBet", ReplyAction="http://tempuri.org/IBettorClientService/GetBetResponse")]
        System.Threading.Tasks.Task<LigaManagerServer.Models.Bet> GetBetAsync(LigaManagerServer.Models.Match match, LigaManagerServer.Models.Bettor bettor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBettorClientServiceChannel : LigaManagerBettorClient.BettorClientService.IBettorClientService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BettorClientServiceClient : System.ServiceModel.ClientBase<LigaManagerBettorClient.BettorClientService.IBettorClientService>, LigaManagerBettorClient.BettorClientService.IBettorClientService {
        
        public BettorClientServiceClient() {
        }
        
        public BettorClientServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BettorClientServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BettorClientServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BettorClientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LigaManagerServer.Models.Match[] GetMatches(LigaManagerServer.Models.Season season) {
            return base.Channel.GetMatches(season);
        }
        
        public System.Threading.Tasks.Task<LigaManagerServer.Models.Match[]> GetMatchesAsync(LigaManagerServer.Models.Season season) {
            return base.Channel.GetMatchesAsync(season);
        }
        
        public LigaManagerServer.Models.Bet[] GetBets(LigaManagerServer.Models.Bettor bettor) {
            return base.Channel.GetBets(bettor);
        }
        
        public System.Threading.Tasks.Task<LigaManagerServer.Models.Bet[]> GetBetsAsync(LigaManagerServer.Models.Bettor bettor) {
            return base.Channel.GetBetsAsync(bettor);
        }
        
        public LigaManagerServer.Models.Bet[] GetAllBets() {
            return base.Channel.GetAllBets();
        }
        
        public System.Threading.Tasks.Task<LigaManagerServer.Models.Bet[]> GetAllBetsAsync() {
            return base.Channel.GetAllBetsAsync();
        }
        
        public LigaManagerServer.Models.Bettor[] GetBettors() {
            return base.Channel.GetBettors();
        }
        
        public System.Threading.Tasks.Task<LigaManagerServer.Models.Bettor[]> GetBettorsAsync() {
            return base.Channel.GetBettorsAsync();
        }
        
        public LigaManagerServer.Models.Bettor GetBettor(string nickname) {
            return base.Channel.GetBettor(nickname);
        }
        
        public System.Threading.Tasks.Task<LigaManagerServer.Models.Bettor> GetBettorAsync(string nickname) {
            return base.Channel.GetBettorAsync(nickname);
        }
        
        public LigaManagerServer.Models.Season[] GetSeasons() {
            return base.Channel.GetSeasons();
        }
        
        public System.Threading.Tasks.Task<LigaManagerServer.Models.Season[]> GetSeasonsAsync() {
            return base.Channel.GetSeasonsAsync();
        }
        
        public LigaManagerServer.Models.SeasonToTeamRelation[] GetTeams(LigaManagerServer.Models.Season season) {
            return base.Channel.GetTeams(season);
        }
        
        public System.Threading.Tasks.Task<LigaManagerServer.Models.SeasonToTeamRelation[]> GetTeamsAsync(LigaManagerServer.Models.Season season) {
            return base.Channel.GetTeamsAsync(season);
        }
        
        public bool IsValidNickname(string name) {
            return base.Channel.IsValidNickname(name);
        }
        
        public System.Threading.Tasks.Task<bool> IsValidNicknameAsync(string name) {
            return base.Channel.IsValidNicknameAsync(name);
        }
        
        public bool AddBet(LigaManagerServer.Models.Bet bet) {
            return base.Channel.AddBet(bet);
        }
        
        public System.Threading.Tasks.Task<bool> AddBetAsync(LigaManagerServer.Models.Bet bet) {
            return base.Channel.AddBetAsync(bet);
        }
        
        public bool ChangeBet(LigaManagerServer.Models.Bet bet) {
            return base.Channel.ChangeBet(bet);
        }
        
        public System.Threading.Tasks.Task<bool> ChangeBetAsync(LigaManagerServer.Models.Bet bet) {
            return base.Channel.ChangeBetAsync(bet);
        }
        
        public LigaManagerServer.Models.Bet GetBet(LigaManagerServer.Models.Match match, LigaManagerServer.Models.Bettor bettor) {
            return base.Channel.GetBet(match, bettor);
        }
        
        public System.Threading.Tasks.Task<LigaManagerServer.Models.Bet> GetBetAsync(LigaManagerServer.Models.Match match, LigaManagerServer.Models.Bettor bettor) {
            return base.Channel.GetBetAsync(match, bettor);
        }
    }
}
